
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
  labels:
    app: golang-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
      - name: golang-api
        image: registry.digitalocean.com/golang-api/golang-api:v1
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:8.0.6
        ports:
        - containerPort: 27017